packages/sdk-react/src/components/userRoles/UserRoleDetails/ExistingUserRoleDetails/UserRoleRow/UserRoleRow.tsx, packages/sdk-react/src/components/userRoles/UserRolesTable/PermissionsCell/PermissionsCell.test.tsx, packages/sdk-react/src/components/userRoles/UserRolesTable/PermissionsCell/PermissionsCell.tsx, packages/sdk-react/src/components/userRoles/UserRolesTable/UserRolesTable.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po
=> feat(DEV-9853): read role details QA updates

.changeset/loud-pillows-juggle.md, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/components/ProductsTable.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/src/core/queries/useProducts.ts
A pagination_token was set as '0', which is incorrect. Replaced with an empty string.
=> fix(DEV-10434): fix initial loading of products in the receivables

CHANGELOG.md
This MR contains changelogs for the 3.9.0 SDK versions.
=> docs(proposal): changelogs for v3.9.0 (DEV-10373)

.changeset/silver-ghosts-notice.md, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/InvoiceDetails.stories.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/src/mocks/payment/paymentHandlers.ts, packages/sdk-react/src/mocks/receivables/receivablesFixture.ts
We have to issue an invoice before generating a payment link because Payments rejects our request if receivable in `Draft` status
=> fix(DEV-10542): Issue an invoice before creating a payment link

CHANGELOG.md
This MR contains changelogs for the 3.10.0 SDK versions.
=> docs(proposal): changelogs for v3.10.0 (DEV-10595) 

.changeset/mean-cougars-train.md, packages/sdk-drop-in/src/drop-in-element.tsx
Add `delegatesFocus` for simple and effective focus management.
=> feat(proposal): add `delegatesFocus` to Drop In component 🪄

.changeset/tender-hotels-explain.md, packages/sdk-react/src/components/receivables/CreditNotesTable/CreditNotesTable.tsx, packages/sdk-react/src/components/receivables/InvoiceCounterpartName.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingReceivableDetails.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/sections/PreviewDetailsSection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/InvoiceTo/InvoiceTo.tsx, packages/sdk-react/src/components/receivables/InvoicesTable/InvoicesTable.tsx, packages/sdk-react/src/components/receivables/QuotesTable/QuotesTable.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po
Add consistent output of the Counterpart name.
**Affected components**
- `<CreditNotesTable/>`
- `<ExistingReceivableDetails/>`
- `<InvoiceTo.tsx/>`
- `<InvoicesTable/>`
- `<QuotesTable/>`
=> feat(DEV-10815): add consistency to receivables Counterpart Name 👤

.changeset/smooth-donkeys-swim.md, packages/sdk-api/src/api/services/ReceivableService.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/CreateReceivables.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/components/ProductsTable.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/components/useCreateInvoiceProductsTable.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/CustomerSection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/EntitySection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/ItemsSection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/PaymentSection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/Section.types.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/validation.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingInvoiceDetails.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingReceivableDetails.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EditInvoiceDetails.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/sections/PreviewCustomerSection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/useExistingInvoiceDetails.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/InvoiceDetails.test.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/src/core/queries/useReceivables.ts, packages/sdk-react/src/mocks/counterparts/vat/counterpartVatFixture.ts, packages/sdk-react/src/mocks/receivables/receivablesFixture.ts, packages/sdk-react/src/mocks/receivables/receivablesHandlers.ts
=> feat(DEV-4699): Provide an ability to edit an invoice

CHANGELOG.md
This commit contains changelogs for the SDK version 3.11.0
=> docs(proposal): changelogs for v3.11.0 (DEV-10765)

.changeset/silent-spiders-grin.md, packages/sdk-react/src/ui/table/TablePagination.tsx
=> fix(DEV-10393): fix table page reset and styles for page size selector

.changeset/hungry-worms-smell.md, .changeset/nice-masks-worry.md, packages/sdk-api/src/api/services/ReceivableService.ts, packages/sdk-react/src/components/receivables/CreditNotesTable/CreditNotesTable.tsx, packages/sdk-react/src/components/receivables/Filters/Filters.tsx, packages/sdk-react/src/components/receivables/Filters/useReceivablesFilters.tsx, packages/sdk-react/src/components/receivables/InvoicesTable/InvoicesTable.tsx, packages/sdk-react/src/components/receivables/QuotesTable/QuotesTable.tsx, packages/sdk-react/src/components/receivables/ReceivablesTable/types.ts, packages/sdk-react/src/components/receivables/consts.ts
Implemented a _"Due Date"_ filter for the Invoices Table to enhance user experience by enabling efficient searching and filtering of invoices based on due dates.
1.  **Invoices Table Update**:
-   Added the _"Due Date"_ filter to the _Invoices Table_, allowing users to filter invoices by due dates.
2.  **Column Update in Invoices Table**:
-   Replaced the `fulfillment_date` column with the `due_date` column in the `<InvoicesTable />` component.
3.  **API Query Parameter**:
-   Integrated the `due_date__lte` parameter to support filtering options.
Users can now filter invoices due before or on a specific date using the `due_date__lte` parameter.
=> feat(DEV-10943): add Invoices Table "Due date" filter ◍

.changeset/quiet-rockets-relate.md, packages/sdk-react/src/components/products/ProductDetails/ProductCreate/CreateProduct.tsx, packages/sdk-react/src/components/products/ProductDetails/ProductEditForm/ProductEditForm.test.tsx, packages/sdk-react/src/components/products/ProductDetails/ProductEditForm/ProductEditForm.tsx, packages/sdk-react/src/components/products/ProductDetails/components/ProductForm/ProductForm.tsx, packages/sdk-react/src/mocks/products/productsFixtures.ts
Key changes:
- **Stabilized product fixture generation:** More predictable and reliable test outcomes.
- **Replaced synthetic event submission with native methods:**  Migrated from using synthetic events to native methods for submitting the form.
=> refactor(proposal): product edit form events & tests stability 🪇

.changeset/cool-turtles-love.md, packages/eslint-plugin/src/config/lingui.js, packages/sdk-react/src/components/payables/PayableDetails/PayableDetails.tsx, packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsInfo/PayableDetailsInfo.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/src/mocks/payables/payablesFixture.ts
The alert will be shown if Payable is in status "Draft" or "New" and the OCR process finishes with an error.
=> feat(DEV-8980): display OCR error message in PayableDetails

packages/sdk-react/src/components/onboarding/hooks/useOnboardingForm.ts
removed code that caused the problems
=> fix(DEV-11697): fix fields input in onboarding

packages/sdk-react/src/components/onboarding/OnboardingPersonsReview/OnboardingAddressView/OnboardingAddressView.tsx, packages/sdk-react/src/components/onboarding/OnboardingPersonsReview/OnboardingReviewStyles/OnboardingReviewStyles.tsx
fix persons step error, when we don't have country info for user 
also fixed styles in table
=> fix(DEV-12024): fix persons step invalid_argument and styles

packages/sdk-react/src/components/onboarding/hooks/useOnboardingEntity.ts, packages/sdk-react/src/components/onboarding/hooks/useOnboardingPerson.ts, packages/sdk-react/src/components/onboarding/utils/index.tsx, packages/sdk-react/src/components/onboarding/utils/showErrorToast.ts
Show toast for common errors in onboarding form (not only errors in fields)
=> fix(DEV-11940): fix toasts for common erorrs

.changeset/brown-geckos-talk.md, packages/sdk-react/src/components/approvalRequests/ApprovalRequestsTable/ApprovalRequestsTable.tsx, packages/sdk-react/src/components/payables/PayablesTable/PayablesTable.tsx, packages/sdk-react/src/components/receivables/CreditNotesTable/CreditNotesTable.tsx, packages/sdk-react/src/components/receivables/InvoicesTable/InvoicesTable.tsx, packages/sdk-react/src/components/receivables/QuotesTable/QuotesTable.tsx, packages/sdk-react/src/core/hooks/useAutosizeGridColumns.ts, packages/sdk-react/src/ui/CounterpartCell/CounterpartCell.tsx, packages/sdk-themes/src/themes/monite.ts
This PR: 
- Reduces amount of layout jumps on page load,
- Preserves column state between page reloads.
=> feat(DEV-12191): improved grid autosize

.changeset/silver-ads-cover.md, packages/sdk-react/src/components/receivables/InvoicesTable/InvoicesTable.tsx
Display recurring icon in the Invoices Table
<details>
<summary>Screenshot</summary>
</details>
=> chore(DEV-11417): display recurring icon in invoices table 🧂

.changeset/afraid-ties-suffer.md, packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartDetails.test.tsx, packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartForm/CounterpartIndividualForm/CounterpartIndividualForm.tsx, packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartForm/CounterpartIndividualForm/validation.tsx, packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartForm/CounterpartOrganizationForm/CounterpartOrganizationForm.tsx, packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartForm/CounterpartOrganizationForm/validation.tsx, packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartForm/CounterpartReminderToggle.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po
=> feat(DEV-12368): Implement toggle to turn reminders on/off on counterpart level

packages/sdk-themes/src/themes/monite.ts
This PR fixes MuiChip icon margin
=> fix(DEV-12285): MuiChip delete icon margin

examples/with-nextjs-and-clerk-auth/src/app/(monite)/user-roles/page.tsx, examples/with-nextjs-and-clerk-auth/src/components/MoniteComponents.tsx, packages/sdk-react/src/components/approvalPolicies/RolesAndPolicies.tsx, packages/sdk-react/src/components/approvalPolicies/index.tsx, packages/sdk-react/src/components/userRoles/UserRoleDetails/UserRoleDetailsDialog/UserRoleDetailsDialog.tsx, packages/sdk-react/src/components/userRoles/UserRoles.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-themes/src/themes/monite.ts
This PR adds Roles & Approvals component to our SDK and demo:
https://monite.slack.com/archives/D07GGK1NJLS/p1725290619096599
=> feat(DEV-12284): roles and approvals dialog

.changeset/metal-rockets-care.md, packages/sdk-react/src/components/onboarding/OnboardingEntityDocuments/OnboardingEntityDocuments.tsx, packages/sdk-react/src/components/onboarding/hooks/useOnboardingRequirements.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/CreateReceivables.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/components/useCreateInvoiceProductsTable.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/EntitySection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/ItemsSection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/validation.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EditInvoiceDetails.tsx, packages/sdk-react/src/core/queries/index.ts, packages/sdk-react/src/core/queries/useMe.ts, packages/sdk-react/src/core/utils/countries.ts
Checks for US entity logic cherry-picked
=> feat(DEV-12598): checks for US entity logic cherry-picked

.changeset/tough-panthers-play.md, packages/sdk-demo/src/apps/Base/Base.tsx, packages/sdk-demo/src/apps/Base/consts.ts, packages/sdk-demo/src/components/Menu/consts.tsx, packages/sdk-demo/src/locales/en/messages.po, packages/sdk-drop-in/tests/iframe.test.ts, packages/sdk-react/mui-styles.d.ts, packages/sdk-react/src/components/approvalPolicies/ApprovalPoliciesTable/ApprovalPoliciesTable.tsx, packages/sdk-react/src/components/approvalPolicies/ApprovalPoliciesTable/Filters/Filters.tsx, packages/sdk-react/src/components/approvalPolicies/ApprovalStatusChip/ApprovalStatusChip.stories.tsx, packages/sdk-react/src/components/approvalPolicies/ApprovalStatusChip/ApprovalStatusChip.tsx, packages/sdk-react/src/components/approvalPolicies/ApprovalStatusChip/index.ts, packages/sdk-react/src/components/approvalPolicies/consts.ts, packages/sdk-react/src/components/approvalRequests/ApprovalRequestsTable/AutocompleteCreatedBy/AutocompleteCreatedBy.tsx, packages/sdk-react/src/components/rolesApprovals/RolesApprovalsTable.tsx, packages/sdk-react/src/components/rolesApprovals/index.ts, packages/sdk-react/src/core/i18n/locales/en/messages.po
=> feat(DEV-12862): Extra fields and combine Roles and Approvals page with tabs + filters

.changeset/breezy-dodos-jog.md, packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsForm/PayableDetailsForm.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/src/mocks/payables/payableHandlers.ts, packages/sdk-react/src/mocks/payables/payablesFixture.ts
This change requests required fields from the API and applies them to the main payable form's fields.
Fields that have already been required remain the same.
=> feat(DEV-12896): apply validation form API to the payable form

.changeset/smart-hounds-camp.md, packages/sdk-react/src/components/approvalPolicies/ApprovalPolicyDetails/ApprovalPolicyForm/ApprovalPolicyForm.tsx
Extra improvements:
- Empty Input Handling for Amount (Non-integer Validation)
- Immediate Validation on Change
=> fix(DEV-12495): extra validation fixes for approval policies

.changeset/tricky-keys-smoke.md, packages/sdk-react/src/components/payables/PayablesTable/components/PayablesTableAction.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po
=> feat(proposal): payment flow integration

examples/with-nextjs-and-clerk-auth/src/app/(monite)/ai-assistant/page.tsx, examples/with-nextjs-and-clerk-auth/src/components/NavigationMenu/NavigationList.tsx, examples/with-nextjs-and-clerk-auth/src/icons/index.ts, examples/with-nextjs-and-clerk-auth/src/locales/en/messages.po
Enabling AI Assistance page in demo back.
Disabling the input and adding a banner-notification about availability.
=> feat(DEV-13140): Show AI Assistant page with banner and disabled inputs

examples/with-nextjs-and-clerk-auth/src/app/(monite)/ai-assistant/page.tsx
Returns old styles for AI Assistance cards content.
=> fix(proposal): return old styles for AI Assistance cards

.changeset/lazy-items-brush.md, packages/sdk-demo/package.json, packages/sdk-demo/vite.config.ts, yarn.lock
=> chore(proposal): add html meta tag to sdk-demo

.changeset/early-rockets-sniff.md, package.json, packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartBankForm/CounterpartBankForm.tsx, packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartView/CounterpartBankView/CounterpartBankView.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po
Added new field bank account holder name for counterpart
=> feat(proposal): add counterpart bank account holder name

.changeset/lucky-pumas-punch.md, packages/sdk-react/src/components/payables/PayableDetails/PayableDetails.test.tsx, packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsCancelModal/PayableDetailsCancelModal.tsx, packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsCancelModal/index.ts, packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsHeader/PayableDetailsHeader.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po
Implementation of a confirmation modal for bill cancelation.
=> feat(DEV-13346): show confirmation modal for bill cancelation

.changeset/chilled-schools-admire.md, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/PaymentSection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/Billing/FullfillmentSummary.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/DeletePaymentTerms.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/DiscountForm.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/PaymentTerms.test.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/PaymentTermsDialog.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/PaymentTermsForm.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/PaymentTermsSummary.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/PaymentTermsSummaryItem.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/index.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/paymentTermsValidation.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/types.ts, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/usePaymentTermsApi.ts, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/src/mocks/paymentTerms/paymentTermsHandlers.ts
Implementation of Payment terms CRUD functionality
=> feat(DEV-12235): Payment terms create/update/delete

.changeset/config.json, .changeset/wicked-parrots-cross.md, packages/sdk-react/src/components/payables/PayableDetails/PayableDetails.test.tsx, packages/sdk-react/src/components/payables/PayableDetails/PayableDetails.tsx, packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsHeader/PayableDetailsHeader.tsx, packages/sdk-react/src/components/payables/PayableDetails/usePayableDetails.tsx, packages/sdk-react/src/components/payables/Payables.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/typings.d.ts
This PR adds the ability to delete payables after they've been canceled to v3 (copied from v4)
=> feat(DEV-12651): v3 Add option to delete canceled payables

.changeset/real-pigs-switch.md, packages/sdk-react/src/components/counterparts/CounterpartDetails/useCounterpartDetails.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/CreateReceivables.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/components/FormErrorDisplay.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/ItemSelector.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/ItemsSection.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/MeasureUnitController.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/TaxRateController.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/VatRateController.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/CounterpartSelector.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/InvoicePreview.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/DeletePaymentTerms.tsx, packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/utils.ts, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/src/core/types/utils.ts, packages/sdk-react/src/core/utils/vatUtils.ts, packages/sdk-react/src/ui/Currency/CurrencyInput.tsx
1. **Display Improvements**
- Tax values are now properly formatted when shown in the UI
- Validation for tax fields now works correctly with proper formatting
2. **Line Item Bug Fixes & Refactoring**
- Added new hooks for better data management, including measure unit mapping and invoice defaults
- Fixed critical bug with measure units restoration in edit flows, preserving custom units
3. **Measure Unit Handling Improvements**
- Enhanced preservation of custom measure unit names
- Added prevention mechanisms for overriding custom values
4. **Form Error Handling Enhancements**
- Improved error management with internal and external error tracking
- Added the FormErrorDisplay component for better error visualization
5. **Autocomplete Improvements**
- Enhanced ItemSelector with better custom …
=> fix(DEV-14661): line item fixes

.changeset/cyan-deers-tickle.md, packages/sdk-react/src/components/payables/PayablesTable/PayablesTable.tsx, packages/sdk-react/src/components/payables/PayablesTable/consts.ts, packages/sdk-react/src/components/payables/PayablesTable/types.ts
Fix typo on `payable.amount_paid` on Payables table (was incorrectly as `payable.paid_amount`).
Jira task [DEV-14699](https://monite.atlassian.net/browse/DEV-14699).
Fixed typo on Payables column. Also renamed a constant for consistency.
Open Payables table, click on the "partially paid" filter, column "paid" should show some amounts.
=> fix(DEV-14699): Fix payable.amount_paid on Payables table

.changeset/stale-tigers-shave.md, packages/sdk-react/src/components/approvalPolicies/RolesAndPolicies.tsx, packages/sdk-react/src/components/userRoles/UserRoleDetails/UserRoleDeleteDialog/UserRoleDeleteDialog.tsx, packages/sdk-react/src/components/userRoles/UserRoleDetails/UserRoleDeleteDialog/index.ts, packages/sdk-react/src/components/userRoles/UserRoleDetails/UserRoleDetailsDialog/UserRoleDetailsDialog.test.tsx, packages/sdk-react/src/components/userRoles/UserRoleDetails/UserRoleDetailsDialog/UserRoleDetailsDialog.tsx, packages/sdk-react/src/components/userRoles/UserRoleDetails/UserRoleEditDialog/UserRoleEditDialog.test.tsx, packages/sdk-react/src/components/userRoles/UserRoleDetails/UserRoleEditDialog/UserRoleEditDialog.tsx, packages/sdk-react/src/components/userRoles/UserRoles.tsx, packages/sdk-react/src/components/userRoles/index.ts, packages/sdk-react/src/components/userRoles/useUserRoles.ts, packages/sdk-react/src/core/i18n/locales/en/messages.po
Improve user roles management by implementing the role delete functionality.
Jira task [DEV-14562](https://monite.atlassian.net/browse/DEV-14562).
Added buttons, dialog, and mutations to delete a user role.
Follow-up of https://github.com/team-monite/monite-sdk/pull/640
=> feat(DEV-14562): SDK improve user roles management delete role

.changeset/tasty-donkeys-relax.md, packages/sdk-react/src/components/onboarding/OnboardingEntity/OnboardingEntityIndividual/OnboardingEntityIndividual.stories.tsx, packages/sdk-react/src/components/onboarding/OnboardingEntity/OnboardingEntityIndividual/OnboardingEntityIndividual.tsx, packages/sdk-react/src/components/onboarding/OnboardingPerson/OnboardingPerson.stories.tsx, packages/sdk-react/src/components/onboarding/OnboardingPerson/OnboardingPerson.tsx, packages/sdk-react/src/components/onboarding/OnboardingPersonsReview/OnboardingPersonView/OnboardingPersonView.stories.tsx, packages/sdk-react/src/components/onboarding/OnboardingPersonsReview/OnboardingPersonView/OnboardingPersonView.tsx, packages/sdk-react/src/core/i18n/locales/en/messages.po
* Changed Onboarding Web component label from "Security Number" to “Full Social Security Number“
* Added related stories
=> fix(DEV-14755): changed security number title, stories

.changeset/modern-kangaroos-tan.md, packages/sdk-react/src/components/financing/components/FinanceBanner.tsx, packages/sdk-react/src/components/financing/hooks/useGetFinancingConnectToken.ts, packages/sdk-react/src/core/i18n/locales/en/messages.po
Added some minor fixes to finance design
- Added loading spinner to the button while it's loading
- Added error handling on the financing_tokens endpoint
- Updated responsiveness on the finance banner
=> feat(DEV-14928): Added minor adjustments to finance design

.changeset/funny-lies-cross.md, packages/sdk-react/src/components/onboarding/Onboarding.stories.tsx, packages/sdk-react/src/components/onboarding/OnboardingBankAccount/OnboardingBankAccount.stories.tsx, packages/sdk-react/src/components/onboarding/OnboardingBankAccount/OnboardingBankAccount.tsx, packages/sdk-react/src/components/onboarding/OnboardingContent/OnboardingContent.tsx, packages/sdk-react/src/components/onboarding/types.ts, packages/sdk-react/src/core/componentSettings/index.ts, packages/sdk-react/src/core/i18n/locales/en/messages.po
**Component Settings**: 
* Added the allowedCurrencies and allowedCountries settings to filter the currency and country selection options presented to the user in the UI on the onboarding bank step
**OnboardingContent.tsx**:
* Logic to utilize these new properties
=> feat(DEV-14886): onboarding currency and country options

.changeset/green-worms-lay.md, packages/sdk-react/src/components/tags/TagFormModal/TagFormModal.tsx, packages/sdk-react/src/components/tags/TagsTable/TagsTable.tsx, packages/sdk-react/src/components/tags/helpers.ts, packages/sdk-react/src/core/i18n/locales/en/messages.po, packages/sdk-react/src/mocks/tags/tagsFixture.ts
Introduce a centralized method for retrieving tag category labels and refactor the tag categories into a dedicated helper file.
Jira ticket: https://monite.atlassian.net/browse/DEV-14916
- Added getTagCategoryLabel helper function.
- Moved const tagCategories into helper file.
1. Open Tags page.
2. Click "create new tag", on the Category field, the option should be properly formatted with capitalization and without underscores.
3. Save the new tag.
4. On the Tags table, the Category column values should be properly formatted with capitalization and without underscores.
=> feat(DEV-14916): Add tag category label getter

packages/sdk-react/src/core/i18n/locales/en/messages.po
Git conflict markers have been removed from the translation file
=> fix(DEV-16302): remove git conflict markers and update translations
