team-monite/monite-sdk

- .github/workflows/version-or-release-packages.yml
Added setting an empty `NPM_TOKEN` for the `Upload to Sentry` task so that you can use upload to Sentry without reverting to patched `.yarnrc.yml`, where `NPM_TOKEN` is the required env variable.
> fix(DEV-10094): Add usage of empty `NPM_TOKEN` to `Upload to Sentry` job

- .github/workflows/merge-gitlab-mr.yml
- .github/workflows/sync-pr-with-gitlab.yml
Added workflows to automate synchronization with GitLab:
1.  **Sync GitHub PR with GitLab:** Triggers when a GitHub PR branch is updated, syncing the branch to GitLab as a submodule.
2.  **Merge GitLab MR on PR Close:** Automates GitLab MR merging when the corresponding GitHub PR is closed.
> feat(DEV-10167): add workflows to synchronize with the GitLab repo submodule

- .github/workflows/contribution-guidelines-check.yml
- .github/workflows/monorepo-main-suite.yaml
- .github/workflows/version-or-release-packages.yml
Added comments to clarify the use of `on: pull_request` and `on: pull_request_target` triggers in GitHub Actions. This is to prevent confusion and align with best practices for security as outlined in the provided articles:
-   [Preventing pwn requests in GitHub Actions](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
-   [GitHub Actions and the threat of malicious pull requests](https://nathandavison.com/blog/github-actions-and-the-threat-of-malicious-pull-requests)
_Additional Changes_
- Fixed syntax highlighting to be compatible with the latest IDEA release
> docs(proposal): add comments to GitHub workflows explaining potential vulnerability issues

- .changeset/fluffy-forks-pull.md
- packages/sdk-react/src/components/products/ProductDetails/ProductEditForm/ProductEditForm.tsx
- packages/sdk-react/src/mocks/products/productsFixtures.ts
If `description` from the server has to be sent as `null` then FE validation couldn't handle it. To fix it we have to set `description` as `''` (empty string) to satisfy validation rules
> fix(DEV-9738): Update default values for the ProductDetails component

- .changeset/pink-moons-repeat.md
- packages/sdk-demo/src/components/Layout/ThemeSelect.tsx
- packages/sdk-react/src/core/hooks/useMenuButton.tsx
Fixed two issues in `sdk-react`:
1.  Stopped event bubbling from `<Menu/>` when wrapped with `<Button/>`, ensuring that clicking on `<Menu/>` does not trigger `<Button/>` actions.
2.  Ensured `<ThemeSelect/>` remains open when switching between Light and Dark modes.
> fix(proposal): allow `<Menu/>` incorrect nesting 🪹

- examples/with-nextjs-and-clerk-auth/src/app/layout.tsx
- examples/with-nextjs-and-clerk-auth/src/app/regenerate-entity/RegenerateOrganizationEntity.tsx
- examples/with-nextjs-and-clerk-auth/src/app/regenerate-entity/page.tsx
- examples/with-nextjs-and-clerk-auth/src/components/RootQueryClientProvider.tsx
- examples/with-nextjs-and-clerk-auth/src/components/ThemeRegistry/RootThemeProvider.tsx
Added a standalone `QueryClientProvider` to the `Layout` for the Next.js demo application, replacing the inherited `QueryClientProvider` from Monite SDK to ensure proper functionality.
> fix(proposal): auth demo query client provider

- .changeset/brave-pigs-give.md
- packages/sdk-react/src/core/context/MoniteContext.tsx
- packages/sdk-react/src/core/context/MoniteI18nProvider.test.tsx
- packages/sdk-react/src/core/context/MoniteI18nProvider.tsx
- packages/sdk-react/src/core/context/MoniteProvider.tsx
- packages/sdk-react/src/core/hooks/useCurrencies.ts
- packages/sdk-react/src/utils/test-utils.tsx
To provide our customers the ability to tailor currency display formats according to their preferences, we've introduced the `currencyNumberFormat` property to the `MoniteLocale` type. This enhancement boosts the flexibility of our locale management and ensures that currency representations can be aligned with user-specific or regional requirements.
Here's how the `currencyNumberFormat` parameter changes the display format:
1.  **Symbol Display (`currencyNumberFormat: { display: 'symbol' }`)**: 
-   Locale: `en-US`
-   Display Example: `$100.00` for an amount of 100 dollars.
-   Locale: `de-DE`
-   Display Example: `100,00 $` for an amount of 100 dollars.
2.  **Code Display (`currencyNumberFormat: { display: 'code' }`)**:
-   Locale: `en-US`
-   Display Example: `USD 100.00` for an amount …
> feat(DEV-10397): add `currencyNumberFormat` to `MoniteLocale` object 🌐

- .changeset/tricky-turtles-sin.md
- packages/sdk-react/src/components/receivables/ReceivablesTable/ReceivablesTable.tsx
This PR proposes changes to the `<ReceivablesTable/>` component to improve its accessibility and ARIA compliance. 
**Key improvements:**
- **Fixes incorrect `aria-controls` references:**  each tab's element correctly references its corresponding tab panel using `aria-controls`.
- Introduces `role="tabpanel"` to each tab's content area to explicitly define them as interactive tab panels.
- Adds `aria-labelledby` to each tab panel
- Type names refactoring
> refactor(proposal): improve `<ReceivablesTable/>` ARIA usage 🧼

- .changeset/sour-insects-rest.md
- packages/sdk-api/src/api/services/ReceivableService.ts
This PR addresses an issue in the `InvoiceTable` tab where the Counterpart filter was using the counterpart's name instead of ID.
**Testing:**
- Manually tested the Counterpart filter in the Invoices Table to confirm that it is now filtering by ID instead of name.
> fix(DEV-10942): filter invoices by Counterpart name in `<InvoicesTable/>` ▧

- .changeset/friendly-windows-compete.md
- packages/sdk-react/src/core/context/MoniteI18nProvider.tsx
- packages/sdk-react/src/utils/compile-lingui-dynamic-messages.test.ts
- packages/sdk-react/src/utils/compile-lingui-dynamic-messages.ts
Intrducing support for multiple translations of the same `msgstr` (message string) based on different `msgctxt` (message context) values. This enhancement enables more accurate and nuanced translations, especially when the same phrase requires different translations depending on the context.
**Key changes:**
- **Updated `compileLinguDynamicMessages` function:** The function now handles an object where keys can be either plain strings representing `msgstr` or objects specifying both `msgstr` and `msgctxt`. For objects with multiple entries, each entry can have an optional `msgctxt` key to define a context-specific translation. This change aligns with the structure used in `.po` files, enabling better support for context-based translations.
- **Adopted `generateMessageId()` for …
> feat(DEV-10391): support multiple translations for the same `msgstr` with different contexts ◈▣

- .changeset/khaki-turkeys-yell.md
- .changeset/modern-cooks-pay.md
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingInvoiceDetails.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingReceivableDetails.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/InvoiceDeleteModal.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/sections/PreviewCustomerSection.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/sections/PreviewItemsSection.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/useExistingInvoiceDetails.tsx
- packages/sdk-react/src/core/i18n/locales/en/messages.po
- packages/sdk-react/src/core/queries/useReceivables.ts
- packages/sdk-react/src/ui/FileViewer/FileViewer.tsx
- packages/sdk-react/src/utils/storybook-utils.tsx
Handle some problems:
1. Show the correct error window for PDF documents with the `refresh` button support
2. Don't show the Submit invoice section if the user can't `Issue` an invoice
3. Handle BE permissions and don't show buttons if there are any restrictions ([task](https://monite.atlassian.net/browse/DEV-10818))
> feat(DEV-8990): Improve InvoiceDetails screen

- .changeset/empty-dots-dress.md
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/sections/PreviewDetailsSection.tsx
Update the "_Fulfillment date_" field in the Invoice Details component to display the correct date format. The previous implementation displayed contact details instead of the fulfillment date.
[📷 Fixed UI screenshot](https://github.com/team-monite/monite-sdk/assets/725645/e2b5517b-a0e3-46a8-9373-e141df3bfe44)
> fix(proposal): display correct information for the "Fulfillment date" field in Invoice Details ⛽

- .changeset/clean-taxis-push.md
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingInvoiceDetails.tsx
- packages/sdk-react/src/ui/FileViewer/FileViewer.tsx
> fix(DEV-10643): fix pdf layout to have fixed pdf toolbar when scroll

- .changeset/silent-paws-divide.md
- packages/sdk-react/src/components/approvalPolicies/ApprovalPoliciesTable/ApprovalPoliciesTable.tsx
- packages/sdk-react/src/components/counterparts/CounterpartsTable/CounterpartsTable.tsx
- packages/sdk-react/src/components/payables/PayablesTable/PayablesTable.tsx
- packages/sdk-react/src/components/products/ProductsTable/ProductsTable.tsx
- packages/sdk-react/src/components/receivables/CreditNotesTable/CreditNotesTable.tsx
- packages/sdk-react/src/components/receivables/InvoicesTable/InvoicesTable.tsx
- packages/sdk-react/src/components/receivables/QuotesTable/QuotesTable.tsx
- packages/sdk-react/src/components/tags/TagsTable/TagsTable.tsx
- packages/sdk-react/src/components/userRoles/UserRolesTable/UserRolesTable.tsx
- packages/sdk-themes/src/themes/monite.ts
Resolved the issue where tables jumped in height and scrollbars appeared during data loading when clicking on the pagination button. This refactor ensures a stable user experience by preventing height changes in tables across the application.
1.  Removed unneeded props from the `monite` theme.
2.  Added `autoHeight` prop usage to the `<DataGrid />` component to prevent incorrect height calculation of tables.
- [🐛 Screencast with the issue](https://github.com/team-monite/monite-sdk/assets/725645/5263cae6-c3b1-43f6-9d7f-5998248c5158)
- [🔧 Screencast with the **fixed** issue](https://github.com/team-monite/monite-sdk/assets/725645/f7a7497e-f5c3-4fec-91e3-f3c775968fc4)
> feat(DEV-10896): fix tables incorrect height calculation 📐

- .changeset/poor-pears-guess.md
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/ItemsSection.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/validation.ts
- packages/sdk-react/src/core/i18n/locales/en/messages.po
- packages/sdk-react/src/mocks/products/productsFixtures.ts
Handle `smallest_amount` if what the user provided `amount` is less than `smallest_amount` we throw an error and forbid to submission of the form
> feat(DEV-8691): Add frontend validation for products with provided `small amount`

- .changeset/quick-cobras-visit.md
- packages/sdk-demo/src/components/Layout/index.tsx
- packages/sdk-demo/src/components/Menu/index.tsx
> fix(DEV-10644): prevent theme selector overlap when menu exceeds viewport height

- .changeset/small-geckos-jog.md
- packages/eslint-plugin/src/rules/mui-require-container-property.ts
- packages/eslint-plugin/src/tests/rules/mui-require-container-property.test.ts
- packages/sdk-react/.eslintrc.json
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingInvoiceDetails.tsx
- packages/sdk-react/src/core/context/MoniteI18nProvider.test.tsx
- packages/sdk-react/src/ui/table/TablePagination.tsx
* Added logic in `mui-require-container-property.ts` to specifically handle cases where `useMenuButton(...)` is used to spread props into MUI components, ensuring the `container` property is included if missing.
* Expanded test coverage in `mui-require-container-property.test.ts` to include scenarios with `useMenuButton(...)` hook, particularly checking for the presence of the `container` property in spread operations.
* Modified ESLint configurations in `.eslintrc.json` within `sdk-react` package to switch the rule from "off" to "error", enforcing strict compliance across the codebase.
* Adjusted various components to directly include or correct the `container` property in their spread attributes to adhere to the updated rule, reducing potential rendering issues in popper-based …
> chore(DEV-11178): Update ESLint Rule mui-require-container-property

- .changeset/eighty-boats-count.md
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/validation.ts
The `smallest_amount` field within `getLineItemsSchema(...)` was previously non-nullable, preventing Invoices from being created for products where this field is not applicable (e.g., has a `null` value). 
This PR makes the `smallest_amount` field nullable, allowing for Invoices to be created for all products regardless of whether they have a defined `smallest_amount`.
> fix(proposal): allow creation of Invoice containing products without `smallest_amount` 0️⃣

- .changeset/gold-avocados-join.md
- packages/sdk-react/src/ui/FileViewer/FileViewer.test.tsx
- packages/sdk-react/src/ui/FileViewer/FileViewer.tsx
When an image was selected instead of a PDF for an invoice, the `PDFObject.embed()` function was still being called, even though the PDF container wasn't rendered. This caused the entire page content to be replaced with the image inside an iframe, as the `ref` wasn't properly set.
We've refactored the `FileViewer` component to correctly handle different file types, particularly distinguishing between PDFs and images.
- Added a check to prevent `PDFObject.embed()` calls for non-PDF files
- Implemented separate rendering logic for PDFs and images:
- For PDFs: Use `PDFFileViewer` component
- For images: Render a simple `<img />` tag with appropriate styling
- Prevents unintended page content replacement when viewing non-PDF files
- Simplifies the codebase by removing redundant conditional …
> fix(DEV-11506): prevent incorrect rendering of images in `<FileViewer />` 😶‍🌫️

- .changeset/spotty-rules-shave.md
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsHeader/PayableDetailsHeader.tsx
Removed the unnecessary `submitInvoice` call in the "Save" invoice action to streamline the Invoice saving process.
> fix(DEV-11735): do not call "Submit Invoice" when saving Payable 💾🪲

- packages/sdk-react/src/components/payables/PayableDetails/PayableDetails.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsForm/PayableDetailsForm.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsHeader/PayableDetailsHeader.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsInfo/PayableDetailsInfo.tsx
- packages/sdk-react/src/core/queries/useEntityUsers.ts
- Avoid requests in `useEntityUserById()` when the user is not provided.
- Add shared unique ID for `<PayableDetailsForm />`.
- Remove unnecessary `submitInvoice` on Save invoice action.
- Remove unused `setEdit` property.
> fix(DEV-11735): payable issues and improvements 🪭

- .changeset/stupid-yaks-care.md
- packages/sdk-react/src/components/counterparts/CounterpartsTable/CounterpartsTable.tsx
This PR updates the `CounterpartsTable` to display the full name of individuals instead of just the first name.
- Display individual full name in `<CounterpartsTable />` instead of just `first_name`.
- Replace unsafe casting with `in` operator.
- Remove unnecessary casting.
> fix(DEV-11734): display Individual Full Name in `<CounterpartsTable/>` 👤

- .changeset/quick-moons-push.md
- .changeset/warm-pets-applaud.md
- packages/eslint-plugin/src/rules/mui-require-container-property.ts
- packages/eslint-plugin/src/tests/rules/mui-require-container-property.test.ts
- packages/sdk-react/src/components/RHF/RHFDatePicker/RHFDatePicker.tsx
- packages/sdk-react/src/components/approvalPolicies/ApprovalPoliciesTable/Filters/Filters.tsx
- packages/sdk-react/src/components/approvalRequests/ApprovalRequestsTable/ApprovalRequestsFilter/ApprovalRequestsFilter.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsForm/PayableDetailsForm.tsx
- packages/sdk-react/src/components/payables/PayablesTable/Filters/Filters.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/EntitySection.tsx
- packages/sdk-react/src/components/receivables/ReceivableFilters/ReceivableFilters.tsx
- packages/sdk-react/src/components/userRoles/UserRolesTable/Filters/Filters.tsx
- packages/sdk-react/src/core/context/MoniteI18nProvider.test.tsx
before:
after:
+ added eslint plugin rule
+ fixed for other DatePickers
> fix(DEV-11937): fix mobile date picker for web component

- .changeset/dirty-peas-drop.md
- .changeset/sixty-hats-deliver.md
- packages/sdk-react/src/components/counterparts/helpers.ts
- packages/sdk-react/src/components/counterparts/heplers.test.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetails.test.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsForm/PayableDetailsForm.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsInfo/PayableDetailsInfo.tsx
- packages/sdk-react/src/components/payables/PayableDetails/usePayableDetails.tsx
- packages/sdk-react/src/components/payables/PayablesTable/PayablesTable.test.tsx
- packages/sdk-react/src/components/payables/PayablesTable/PayablesTable.tsx
- packages/sdk-react/src/components/payables/consts.ts
- packages/sdk-react/src/core/i18n/locales/en/messages.po
This Pull Request introduces the following updates:
1. **Two Icon States for Counterpart**:
•  **State 1**: Counterpart not found in the system.
•  **State 2**: Counterpart found but not selected in the document.
•  Added two images to illustrate these states with appropriate color indications.
•  **Note**: If a Counterpart is already selected for the Payable, no icon will be displayed.
2. **Automatic Selection of Counterpart in Payable Editing Form**:
•  Implemented functionality to automatically select the appropriate Counterpart in the Payable editing form.
•  If a Counterpart is not selected for a Payable but is available from counterpart_raw_data, it will be auto-selected.
<details>
<summary>Screenshots 🖥️</summary>
State 1: Counterpart not found in the system.
State 2: Counterpart …
> feat(DEV-11928): enhanced Counterpart Handling for Payables with OCR processing 🤖

- packages/sdk-react/src/components/onboarding/hooks/useOnboardingEntity.ts
- packages/sdk-react/src/components/onboarding/hooks/useOnboardingPerson.ts
remove error toast for entities and persons as we have error messages near the fields
> fix(DEV-12020): remove duplicate error notifications for persons and entity editing

- .github/workflows/monorepo-main-suite.yaml
- .github/workflows/release-packages.yml
- .github/workflows/version-packages.yml
Update [`team-monite/setup-yarn-project-action`](https://github.com/team-monite/setup-yarn-project-action) to the latest version with Node.js 20.x to be compatible with CI.
> chore(proposal): use the latest `team-monite/setup-yarn-project-action`

- .changeset/breezy-bugs-begin.md
- packages/sdk-demo/src/components/Layout/index.tsx
- packages/sdk-react/src/components/approvalPolicies/ApprovalPoliciesTable/ApprovalPoliciesTable.stories.tsx
- packages/sdk-react/src/components/approvalPolicies/ApprovalPoliciesTable/ApprovalPoliciesTable.tsx
- packages/sdk-react/src/components/approvalRequests/ApprovalRequestsTable/ApprovalRequestsTable.stories.tsx
- packages/sdk-react/src/components/approvalRequests/ApprovalRequestsTable/ApprovalRequestsTable.tsx
- packages/sdk-react/src/components/counterparts/CounterpartsTable/CounterpartsTable.stories.tsx
- packages/sdk-react/src/components/counterparts/CounterpartsTable/CounterpartsTable.tsx
- packages/sdk-react/src/components/payables/PayablesTable/PayablesTable.stories.tsx
- packages/sdk-react/src/components/payables/PayablesTable/PayablesTable.tsx
- packages/sdk-react/src/components/products/ProductsTable/ProductsTable.stories.tsx
- packages/sdk-react/src/components/products/ProductsTable/ProductsTable.tsx
- packages/sdk-react/src/components/receivables/CreditNotesTable/CreditNotesTable.stories.tsx
- packages/sdk-react/src/components/receivables/CreditNotesTable/CreditNotesTable.tsx
- packages/sdk-react/src/components/receivables/InvoicesTable/InvoicesTable.stories.tsx
- packages/sdk-react/src/components/receivables/InvoicesTable/InvoicesTable.tsx
- packages/sdk-react/src/components/receivables/QuotesTable/QuotesTable.stories.tsx
- packages/sdk-react/src/components/receivables/QuotesTable/QuotesTable.tsx
- packages/sdk-react/src/components/receivables/ReceivablesTable/ReceivablesTable.stories.tsx
- packages/sdk-react/src/components/receivables/ReceivablesTable/ReceivablesTable.tsx
- packages/sdk-react/src/components/tags/Tags.stories.tsx
- packages/sdk-react/src/components/tags/TagsTable/TagsTable.stories.tsx
- packages/sdk-react/src/components/tags/TagsTable/TagsTable.tsx
- packages/sdk-react/src/components/userRoles/UserRolesTable/UserRolesTable.tsx
Styles for table components were updated and autoHeight property was removed.
Now all tables reproduce the default MUI DataGrid behavior, they require a parent container with intrinsic dimensions.
Advantages:
- we don't force extra property (autoHeight). This property is not recommended in some cases
- the table component could be embedded in a parent block with absolute or dynamic height. It will grow till the bottom of the parent container and leave the content area scrollable. Examples are in the Storybook and Demo project.
> fix(DEV-12158): use flex for datagrid height instead of absolute unit px

- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/ReminderForm/OverdueReminderForm.tsx
Do not display empty `<Alert/>` if there is no error in the reminder form
> fix(DEV-11981): do not display empty `<Alert/>` if there is no error in the reminder form

- .changeset/small-dryers-happen.md
- packages/sdk-themes/src/themes/monite.ts
This PR hides cell selection indicator that appears on cell click, but it doesn't gives any value.
> fix(DEV-12351): hide cell selection indicator

- .changeset/funny-apples-tell.md
- packages/sdk-demo/src/hooks/useThemeConfig.tsx
- packages/sdk-react/mui-styles.d.ts
- packages/sdk-react/src/components/approvalRequests/ApprovalRequestsTable/ApprovalRequestStatusChip/ApprovalRequestStatusChip.tsx
- packages/sdk-react/src/components/approvalRequests/ApprovalRequestsTable/ApprovalRequestStatusChip/index.ts
- packages/sdk-react/src/components/payables/PayableStatusChip/PayableStatusChip.tsx
- packages/sdk-react/src/components/payables/PayableStatusChip/index.ts
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/OverviewTabPanel.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/ReceivableRecurrence/InvoiceRecurrenceIterations.tsx
- packages/sdk-react/src/components/receivables/InvoiceRecurrenceIterationStatusChip/InvoiceRecurrenceIterationStatusChip.tsx
- packages/sdk-react/src/components/receivables/InvoiceRecurrenceStatusChip/InvoiceRecurrenceStatusChip.tsx
- packages/sdk-react/src/components/receivables/InvoiceStatusChip/InvoiceStatusChip.tsx
- packages/sdk-react/src/components/receivables/InvoiceStatusChip/index.ts
- Unified status chip interfaces and removed unnecessary properties from styling components.
- Restored status chip size control to customer configuration(_no default size as previously_).
- Disabled icon displaying for the SDK Demo Monite Theme
<details>
<summary>Screenshots</summary>
</details>
> chore(DEV-11417): refine status icons 🤌

- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/CreateReceivables.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/components/useCreateInvoiceProductsTable.ts
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/EntitySection.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/ItemsSection.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/validation.ts
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EditInvoiceDetails.tsx
- packages/sdk-react/src/core/utils/countries.ts
- Use tax value for US entities during invoice creation.
- Don't require counterpart vat id on create receivable for US based counterparts
> feat(DEV-12499): use tax value for us entity during invoice creation

- .changeset/neat-dolls-push.md
- examples/with-nextjs-and-clerk-auth/package.json
- packages/sdk-react/package.json
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/CreateReceivables.test.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/CreateReceivables.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/components/ProductsTable.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/CustomerSection.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/ItemsSection.tsx
- packages/sdk-react/src/components/receivables/Receivables.test.tsx
- packages/sdk-react/src/components/receivables/Receivables.tsx
- packages/sdk-react/src/mocks/counterparts/address/counterpartsAddressesHandlers.ts
- packages/sdk-react/src/mocks/entities/entitiesFixture.ts
- packages/sdk-react/src/setupTests.tsx
- packages/sdk-react/src/utils/test-utils.tsx
- yarn.lock
This PR opens invoice for editing immediately after its creation. Previously the user were directed back to the invoices list.
The PR contains a long test that fills required fields when creating a new Receivable. I didn't mock nested components because we had a broken test that tested Receivable creation. Therefore my longer test both restores the disabled test from 2022 and tests the new receivable creation flow.
> feat(DEV-12593): Merge create/preview steps of invoice creation into a single flow

- .changeset/odd-horses-rest.md
- packages/sdk-react/mui-styles.d.ts
- packages/sdk-react/src/components/receivables/CreditNotesTable/CreditNotesTable.tsx
- packages/sdk-react/src/components/receivables/InvoicesTable/InvoicesTable.tsx
- packages/sdk-react/src/components/receivables/QuotesTable/QuotesTable.tsx
- packages/sdk-react/src/components/receivables/ReceivableFilters/ReceivableFilters.tsx
- packages/sdk-react/src/components/receivables/ReceivableFilters/index.ts
- packages/sdk-react/src/components/receivables/ReceivableFilters/useReceivablesFilters.tsx
- packages/sdk-react/src/components/receivables/Receivables.tsx
- packages/sdk-react/src/components/receivables/ReceivablesTable/ReceivablesTable.stories.tsx
- packages/sdk-react/src/components/receivables/ReceivablesTable/ReceivablesTable.test.tsx
- packages/sdk-react/src/components/receivables/ReceivablesTable/ReceivablesTable.tsx
- packages/sdk-react/src/components/receivables/ReceivablesTable/types.ts
- packages/sdk-react/src/core/context/MoniteContext.tsx
- packages/sdk-react/src/core/context/MoniteProvider.tsx
- packages/sdk-react/src/core/i18n/locales/en/messages.po
- packages/sdk-react/src/core/utils/createThemeWithDefaults.ts
- packages/sdk-react/src/ui/SearchField/SearchField.tsx
- packages/sdk-react/src/utils/ExtendThemeProvider.tsx
- packages/sdk-react/src/utils/test-utils.tsx
- Added support for configuring custom tabs in Receivables Tables using MUI Theming.
- Maintained backward compatibility with default tabs: Invoices, Quotes, and Credit Notes.
- Updated the `<ReceivablesTable/>` component to use numeric tab indices instead of `ReceivablesTableTabEnum`.
- Changed default tab indices:
- **Invoices**: 0
- **Quotes**: 1
- **Credit Notes**: 2
> feat(DEV-12231): custom Tabs for Receivables 🎲

- .changeset/pretty-parrots-fold.md
- packages/sdk-react/mui-styles.d.ts
- packages/sdk-themes/tsconfig.json
After this patch it highlights unexisted properties
> chore(proposal): more strict typing system for monite.ts

- .changeset/flat-walls-reflect.md
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsForm/PayableDetailsForm.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsForm/helpers.ts
Ready for review. Please let me know if I should include tests.
Current result:
https://github.com/user-attachments/assets/0f7f40a7-6db7-4e03-b676-e0ae0c5010ee
-> Default bank is selected when vendor is selected
-> Default bank changes accordingly when currency changes
-> Bank selection is cleared when different vendor is selected
> fix(DEV-13389): default bank account automatically chosen

- .changeset/spicy-toes-play.md
- packages/sdk-react/src/components/userRoles/UserRoleDetails/UserRoleDetailsDialog/UserRoleDetailsDialog.tsx
Removed `Go to docs` from user-roles modal
> fix(DEV-13836): removed goto docs link from UserRoleDetailsDialog

- .changeset/lazy-rabbits-obey.md
- packages/sdk-react/src/components/products/ProductDetails/ProductCreate/CreateProduct.tsx
- packages/sdk-react/src/components/products/ProductDetails/components/ProductForm/ProductForm.tsx
The Create component acts as an aggregator of default values, combining:
- Base defaults
- API-provided defaults
- Parent-provided defaults (highest priority)
defaultValues logic:
- Wait for data to load before setting defaults (units and entity settings)
- Use first measure unit as default (measureUnits?.data?.[0]?.id)
- Use entity's default currency (entitySettings?.currency?.default)  
ProductForm.tsx
- Removed redundant useMemo for defaultValues since they're already memoized in parent
- Added form reset functionality using useEffect to handle default value changes
> feat(DEV-14165): product creation default values

- .changeset/five-brooms-sparkle.md
- packages/sdk-react/src/components/onboarding/hooks/useOnboardingPerson.ts
- packages/sdk-react/src/components/onboarding/transformers/commonDataTransformers.ts
Schema Mismatch: The API's PersonResponse schema includes an id field, which is returned when fetching a person. However, the OptionalPersonRequest schema used for updates explicitly disallows this field with "additionalProperties": false.
Data Flow Issue: When updating a person, the application was using the complete person object (including the id field) from the previous API response as the basis for the update request. The enrichFieldsByValues function was preserving all fields from the original object, including those that shouldn't be sent back to the API.
1. Added type-safe filtering of request body fields to prevent "Extra inputs are not permitted" error
- Created `EXCLUDED_REQUEST_FIELDS` constant with `id` field that should not be sent in update requests
- Implemented …
> fix(DEV-14402): remove special fileds like id from updatePerson payloads

- .changeset/rotten-lizards-sleep.md
- packages/sdk-react/src/components/Dialog/index.ts
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.form.components.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.test.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.tsx
- packages/sdk-react/src/core/i18n/locales/en/messages.po
- packages/sdk-react/src/mocks/counterparts/contact/counterpartContactHandlers.ts
- packages/sdk-react/src/mocks/receivables/receivablesFixture.ts
- packages/sdk-react/src/mocks/receivables/receivablesHandlers.ts
- EmailInvoiceDetails has been reorganized so that buttons have access to the parent form's context
- Form components (`Form`, `RecipientSelector`, `FormContent`) have been extracted into a separate file `EmailInvoiceDetails.form.components.tsx`
- Added tests for EmailInvoiceDetails covering:
- Pre-population of email details
- Issue and send button visibility
- Issue and send flow in compose view
- Preview and issue-send flow functionality
> fix(DEV-14109): issue and send fixed on the preview page

- .changeset/nervous-llamas-battle.md
- packages/sdk-drop-in/src/lib/MoniteEvents.ts
- packages/sdk-react/src/components/onboarding/Onboarding.tsx
- packages/sdk-react/src/components/onboarding/OnboardingBankAccount/OnboardingBankAccount.tsx
- packages/sdk-react/src/components/onboarding/OnboardingCompleted/OnboardingCompleted.tsx
- packages/sdk-react/src/components/onboarding/OnboardingContent/OnboardingContent.tsx
- packages/sdk-react/src/components/onboarding/helpers.ts
- packages/sdk-react/src/components/onboarding/hooks/useOnboardingBankAccount.ts
- packages/sdk-react/src/components/onboarding/index.ts
- packages/sdk-react/src/components/onboarding/types.ts
- packages/sdk-react/src/components/receivables/Financing/FinanceInvoice/FinanceInvoice.tsx
- packages/sdk-react/src/components/receivables/Financing/hooks/useWorkingCapitalOnboarding.ts
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingInvoiceDetails.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.test.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/Overview.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/OverviewTabPanel.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/InvoiceDetails.types.ts
- packages/sdk-react/src/components/receivables/Receivables.tsx
- packages/sdk-react/src/core/componentSettings/index.ts
- packages/sdk-react/src/core/i18n/locales/en/messages.po
Added the following event flows:
1. First Invoice Sent:
Triggered when an email is sent for the first invoice
onSendEmail in InvoiceDetails provides isFirstInvoice flag
If isFirstInvoice is true, onFirstInvoiceSent callback is called
2. Bank Account Complete:
Triggered when bank account setup is completed
onPaymentOnboardingCompleted callback is called from the onboarding flow
3. Working Capital Onboarding Complete:
Triggered when working capital onboarding status changes to 'ONBOARDED'
onWorkingCapitalOnboardingCompleted callback is called
TODO:
[ ✔️ ] Clean up the types, lint errors and translations (remove unused timestamps etc)
[ ✔️ ] Rebase on Main
> feat(DEV-14246): onboarding + send invoice email events

- .changeset/spotty-ladybugs-obey.md
- packages/sdk-react/src/components/Dialog/Dialog.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/PaymentTermsDialog.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/paymentTermsValidation.ts
- packages/sdk-react/src/core/hooks/useHandleDialogCloseFocus.ts
- packages/sdk-react/src/core/i18n/locales/en/messages.po
1.  **Validation Fix:**
*   Updated the Yup validation schema in `paymentTermsValidation.ts` by adding `.nullable()` to the `term_1` and `term_2` object schemas. This explicitly allows `null` as a valid value, resolving the primary modification bug
2.  **Accessibility (Focus Management):**
*   Created a new reusable hook `useHandleDialogCloseFocus` (in `src/core/hooks/`) to manage focus when a dialog closes
3.  **Ref Forwarding:**
*   Modified the custom `Dialog` component (`src/components/Dialog/Dialog.tsx`) and its internal `DialogBase` component to correctly use `React.forwardRef`. This allows the `ref` from `useHandleDialogCloseFocus` to be passed down to the underlying MUI `Dialog`
4.  **Semantic HTML:**
*   Fixed the DOM nesting warning in `PaymentTermsDialog` by removing the nested …
> fix(DEV-14690): payment terms update validation fixed, dialog close focus hook

- .changeset/nervous-owls-clean.md
- packages/sdk-react/src/components/receivables/ReceivableFilters/ReceivableFilters.tsx
Feature overview:
All customers dropdown in receivables filter was not ordered alphabetically
Changes Made
Ordered customers dropdown alphabetically in receivables table
> feat(DEV-14658): Sort alphabetically all customers filter dropdown list

- .changeset/tame-tables-battle.md
- packages/sdk-drop-in/src/lib/MoniteEvents.ts
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/ExistingInvoiceDetails.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.test.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/ExistingInvoiceDetails/components/EmailInvoiceDetails.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/InvoiceDetails.types.ts
- packages/sdk-react/src/components/receivables/Receivables.tsx
- packages/sdk-react/src/core/componentSettings/index.ts
- packages/sdk-react/src/core/i18n/locales/en/messages.po
**Motivation**
The concept of a "first invoice sent" event was removed because there is no reliable way on the client-side to determine if an invoice being sent is definitively the *first* one for an entity.
**Changes Made**
*   **Renamed Event Callback:** Renamed the `onFirstInvoiceSent` callback prop to `onInvoiceSent` in:
*   **Renamed Event Type:** Renamed the `MoniteEventTypes.FIRST_INVOICE_SENT` enum member to `MoniteEventTypes.INVOICE_SENT` and updated its associated string value from `'invoice.first_sent'` to `'invoice.sent'` in `packages/sdk-drop-in/src/lib/MoniteEvents.ts`.
> feat(DEV-14726): first invoice sent event renamed to invoice sent

- .changeset/eighty-grapes-collect.md
- packages/sdk-react/src/components/onboarding/OnboardingBankAccount/OnboardingBankAccount.tsx
- packages/sdk-react/src/components/payables/PayablesTable/PayablesTable.tsx
Payables table: prevent row click (and disable hover effect) for rows of payables with OCR status in processing.
https://monite.atlassian.net/browse/DEV-14646
- changed the onRowClick prop of the DataGrid to trigger if status is not processing.
- added 'ocr-processing' className to rows that have OCR status in procesing and disable hover effects for that className.
1. Open Payables table.
2. Click "add new bill" and submit a PDF file.
3. Check the first row, that shows "Processing file....", the row should not be clickable and have no hoverable effects.
> feat(DEV-14646): Payables table prevent row click while processing OCR status

- .changeset/angry-bats-cough.md
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/InvoicePreview.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/DiscountForm.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/PaymentTermsForm.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/PaymentTerms/PaymentTermsSummary.tsx
- packages/sdk-react/src/core/i18n/locales/en/messages.po
*   **`DiscountForm.tsx`:** Modified the discount input field. It now converts the input to the required internal format (minor units, eg, 5 -> 500) before submitting it.
*   **`PaymentTermsSummary.tsx` & `InvoicePreview.tsx`:** Updated to format the internal discount value (minor units) correctly for display in major units (eg 500 -> 5)
*   **`PaymentTermsForm.tsx`:** Adjusted the form submission logic to directly send the discount value in its internal format (minor units) to the API
> fix(DEV-14922): payment terms discount units are converted to minor for API-related operations

- .changeset/few-fireants-kick.md
- packages/sdk-react/src/core/utils/getBankAccountName.tsx
Fix Payable Counterpart Bank Account selection to show Bank Account name.
Jira ticket: https://monite.atlassian.net/browse/DEV-14898
- Changed util `getBankAccountName`:
- correct type of variable bankAccount;
- return the name property of bankAccount.
1. Open a Payable, edit, select a vendor/counterpart.
2. On the bank account field, it should show the bank account name. If the bank account is the default for the currency, the bank account name should also be appended with "(default)".
> fix(DEV-14898): Counterpart bank account selection show bank account name

- .changeset/polite-cobras-listen.md
- packages/sdk-demo/src/components/AppMoniteProvider.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/CreateReceivables.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/sections/components/InvoicePreview.tsx
- packages/sdk-react/src/components/receivables/components/BankAccountDeleteModal.tsx
- packages/sdk-react/src/components/receivables/components/BankAccountFormContent.tsx
- packages/sdk-react/src/components/receivables/components/BankAccountFormDialog.tsx
- packages/sdk-react/src/components/receivables/components/BankAccountSection.tsx
- packages/sdk-react/src/components/receivables/hooks/useCreateEntityBankAccount.ts
- packages/sdk-react/src/components/receivables/hooks/useSetDefaultBankAccount.ts
- packages/sdk-react/src/components/receivables/hooks/useUpdateEntityBankAccount.ts
- packages/sdk-react/src/components/receivables/utils/prepareBankAccountPayload.ts
- packages/sdk-react/src/core/i18n/locales/en/messages.po
- Added proper error handling on bank account creation when it fails displaying the actual error message instead of a generic one
- Updated invoice preview with bank account information (This is probably a temporary fix because we might replace the current preview with the new templates)
- Updated delete bank account modal visuals to be more like the figma version
- Fixed issue displaying undefined when the account was EUR, it was undefined because it was trying to read account number but EUR accounts only have IBAN
- Removed alert message and delete button from default bank account edit states
> feat(DEV-14965): Bank account creation hotfixes

- .changeset/mean-pumpkins-bow.md
- packages/sdk-react/src/components/counterparts/components/CounterpartAutocomplete.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsForm/PayableDetailsForm.tsx
Automatically select the Counterpart default bank account when selecting a Counterpart on the Payable details form. Add button to add bank account on bank account select input.
Jira ticket: https://monite.atlassian.net/browse/DEV-14899
- Changed useEffects in PayableDetailsForm to auto select bank account.
- Added button to "add bank account" on bank account select input of PayableDetailsForm. 
- Added trigger form validation on value changes on CounterpartAutocomplete.
- Moved CounterpartDetails dialog from CounterpartAutocomplete to PayableDetailsForm.
- Organized useEffects order in PayableDetailsForm.
1. Open a new Payable, select one Counterpart, should automatically select the default bank account, if the currency matches.
2. If currency does not match, change the payable currency …
> fix(DEV-14899): Auto select Counterpart bank account on Counterpat selection

- .changeset/tough-pans-retire.md
- packages/sdk-react/src/components/onboarding/OnboardingBusinessProfile/OnboardingBusinessProfile.tsx
- packages/sdk-react/src/components/onboarding/validators/validationSchemas.ts
- packages/sdk-react/src/core/i18n/locales/en/messages.po
* Changed the field label from "URL" to "Business URL" to make the purpose clearer
* Updated the tooltip text to: "This can be a website, social media profile link or any other unique reachable URL that describes the account's business nature."
These changes guide users to understand they can provide social media profiles or other online presence links instead of a formal business website.
> feat(DEV-14979): Business website -> URL, upd alert info

- .changeset/mean-pumpkins-bow.md
- packages/sdk-react/src/components/counterparts/components/CounterpartAutocomplete.tsx
- packages/sdk-react/src/components/payables/PayableDetails/PayableDetailsForm/PayableDetailsForm.tsx
> [!NOTE]
> This PR is a duplicate from https://github.com/team-monite/monite-sdk/pull/703, no code changes from it.
> The only difference is this PR targets the `main` branch; the other PR was incorrectly merged into another branch not main.
> Original PR description follows.
Automatically select the Counterpart default bank account when selecting a Counterpart on the Payable details form. Add button to add bank account on bank account select input.
Jira ticket: https://monite.atlassian.net/browse/DEV-14899
- Changed useEffects in PayableDetailsForm to auto select bank account.
- Added button to "add bank account" on bank account select input of PayableDetailsForm. 
- Added trigger form validation on value changes on CounterpartAutocomplete.
- Moved CounterpartDetails dialog from …
> fix(DEV-14899): Auto select Counterpart bank account on Counterpat selection [main]

- .changeset/little-peaches-vanish.md
- packages/sdk-react/src/components/RHF/RHFAutocomplete/CountryOption/CountryOption.tsx
- packages/sdk-react/src/components/RHF/RHFAutocomplete/CountryOption/index.ts
- packages/sdk-react/src/components/RHF/RHFAutocomplete/RHFAutocomplete.tsx
- packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartAddressForm/CounterpartAddressForm.tsx
- packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartAddressFormUpdate/CounterpartAddressFormUpdate.tsx
- packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartBankForm/CounterpartBankForm.tsx
- packages/sdk-react/src/components/counterparts/CounterpartDetails/CounterpartVatForm/CounterpartVatForm.tsx
- packages/sdk-react/src/components/onboarding/OnboardingAddress/OnboardingAddress.tsx
- packages/sdk-react/src/components/onboarding/OnboardingBankAccount/OnboardingBankAccount.tsx
- packages/sdk-react/src/components/receivables/InvoiceDetails/CreateReceivable/CreateReceivables.tsx
- packages/sdk-react/src/components/receivables/components/BankAccountFormContent.tsx
- packages/sdk-react/src/components/receivables/components/FormSelect.tsx
- packages/sdk-react/src/core/i18n/locales/en/messages.po
- packages/sdk-react/src/core/utils/selectHelpers.ts
- packages/sdk-react/src/ui/Country/CountryFlag.tsx
- packages/sdk-react/src/ui/Country/CountryInput.tsx
- packages/sdk-react/src/ui/Country/CountryOption.tsx
- packages/sdk-react/src/ui/Country/MoniteCountry.tsx
- packages/sdk-react/src/ui/Country/index.tsx
**Changes:**
*   Introduced `<MoniteCountry />` as the standard component for country selection.
*   Refactored related sub-components (`CountryOption`, `CountryInput`, `CountryFlag`) to support `MoniteCountry` and fix bugs related to search highlighting, input focus errors, and error message display.
*   Replaced inconsistent country selectors in various forms with `<MoniteCountry />`.
*   Removed redundant option-generation logic from affected forms.
**Affected UI Locations:**
*   **Counterpart Forms:** Address (Create/Update), Bank Account (Create/Update), VAT ID (Create/Update).
*   **Receivables:** Entity Bank Account Form (Settings -> Bank Accounts).
*   **Onboarding Flow:** Bank Account Step, Address Step(s).
> fix(DEV-14226): country selector

- packages/sdk-react/src/components/aiAssistant/components/AssistantButtons/AssistantButtons.tsx
- packages/sdk-react/src/components/aiAssistant/components/AssistantMessage/AssistantMessage.tsx
- packages/sdk-react/src/components/aiAssistant/components/MessageList/MessageList.tsx
As currently a streaming is not a real streaming but just backend emulation of it, it was decided to add animation to a new assistant message when it is recevied on the client and remove streaming emulation
> feat(proposal): add animation to assistant message
